### ISSUE TITLE
Wrong conversion rate crypto to USD in leaderboard

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1546]
In these two campaigns leaderboard the conversion rate of crypto to USD not working properly. I guess it is because the donations are too small, bu I am no sure.
[Buy books of Kant](https://develop.giveth.io/campaigns/5eca16b999915a4eca2c71b0)
[promote Plato philosophy](https://develop.giveth.io/campaigns/5eca6a1c99915a4eca2c7201)

![image](https://user-images.githubusercontent.com/65175075/100523398-7bc8af00-31c5-11eb-98d4-e6fcb760ff81.png)

**Comment by aminlatifi** [comment]
It should be fixed not by giveth/feathers-giveth#280

**Comment by horus2021** [comment]
@aminlatifi  For the first line (it is delegat)  I still see wrong conversion rate.
[promote Plato philosophy](https://develop.giveth.io/campaigns/5eca6a1c99915a4eca2c7201)
![image](https://user-images.githubusercontent.com/65175075/100552387-2e6b4100-329c-11eb-9063-797974d0ab93.png)

**Comment by aminlatifi** [comment]
> @aminlatifi For the first line (it is delegat) I still see wrong conversion rate.
> [promote Plato philosophy](https://develop.giveth.io/campaigns/5eca6a1c99915a4eca2c7201)
> ![image](https://user-images.githubusercontent.com/65175075/100552387-2e6b4100-329c-11eb-9063-797974d0ab93.png)

That was manually filled

**Comment by horus2021** [comment]
It works. @aminlatifi  Great Work!
