### ISSUE TITLE
3 small improvements to Token Donation

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#544]
1. This should say DAI not ETH:
<img width="1440" alt="screen shot 2018-11-30 at 6 41 03 pm" src="https://user-images.githubusercontent.com/14945613/49305505-b82a7d00-f4cf-11e8-9cd1-3b356e825966.png">

2. After the first transaction approving the Bridge to take DAI the saving... is "greyed" out, but i hope we can have a little more hand holding to keep it in the user mind that they are not done donating. It should have some sort of popup reconfirming that there is a second Metamask TX about to pop up. 

The first screen is great tho, that warns them that there will be 2 txs... we just to keep them updated on their progress...

3. https://beta.giveth.io/dacs/5b37da13a239ac21b383d4da here you can see it says ETH instead of DAI
<img width="862" alt="screen shot 2018-11-30 at 7 30 39 pm" src="https://user-images.githubusercontent.com/14945613/49307798-95e82d80-f4d6-11e8-800a-a947b91ceb0f.png">

**Comment by satyavh** [comment]
2 does not cause 3 :-)

>It should have some sort of popup reconfirming that there is a second Metamask TX about to pop up.
Yes that was there, but the code that took care of that got very interesting during the complex merge we went through. I fixed it now :-)

**Comment by satyavh** [comment]
Also see https://github.com/Giveth/feathers-giveth/commit/4d4e0b61a04464e07a32d0ebcac3a05f636a03d2

**Comment by GriffGreen** [comment]
The flow around the double tx is great! Metamask pops up and its easy... but `Fix #544 - showing notification while waiting for 2nd donation tx` doesnt quite fix the problem.

The flag that got added disappears after 5 seconds... but the user has to sit there for about 90 seconds waiting for the tx... it would be nice if the flag stayed (you had to close it) ... i assume it will be easiest to be like the pop up that was there before... just telling the user that its going to take a sec.

**Comment by GriffGreen** [comment]
I have added many other issues... some of them in the title have "(required fix for DAI reward)" :-D these are the ones i feel are required for DAI to be considered implemented... There will likely be more too
