### ISSUE TITLE
Double donations in a DAC

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#598]
<img width="1014" alt="screen shot 2018-12-28 at 7 32 49 am" src="https://user-images.githubusercontent.com/14945613/50505243-d5248280-0a72-11e9-9028-c5793f196dad.png">

https://beta.giveth.io/dacs/5b48c6f9b89c2175b538de66

**Comment by perissology** [comment]
okay, this should be fixed in https://github.com/Giveth/feathers-giveth/commit/2000c293f3a208c54f0761b023b61bc34017b501....

The "unknown" status is actually failed.

This happened because you have a pledge w/ a non 0 amount of DAI (due to previous bugs, but this should appear as a delegation for you). We had some naive logic to determine if a 'Transfer' is an initial donation or not, that did not support this case.

This should be fixed, but the only way to know for sure if for you to make another DAI donation from the 0x839 account.

Leaving open until you make another donation & verify this is fixed.

**Comment by GriffGreen** [comment]
#605

**Comment by GriffGreen** [comment]
Still getting the unknown error
<img width="975" alt="screen shot 2019-01-03 at 7 56 30 am" src="https://user-images.githubusercontent.com/14945613/50626284-976da100-0f2d-11e9-8e38-ddaa6da09fab.png">
https://etherscan.io/tx/0x1a9b93d9661243c5ac557fd08cabee41f96586a6093e924da8751193f771e3d9
This donation isn't showing up as being able to be delegated in L's Unicorn DAC Delegations.

Tho interestingly enough... this morning I also made 2 different ETH donations
The first one:
https://etherscan.io/tx/0x83b83569fb0700425285e50cb72c1ddcc32908f3673802e1dd68ce97622ef375
Comes up as a double donation, an unknown and a good one... but is able to be delegated and the second one:  
https://etherscan.io/tx/0x731fe1bedea6f358ad72bb7a9eaa4401e9fb33a1b0550ce5734bdbf5a086b5e6
actually worked perfectly fine!

Well both of them worked fine and can both be delegated its just for some reason one of them came up as unknown...

so yeah in summary i made 3 donations

1. In ETH, came up as a double donation, one "unknown" and one "ready for delegation" and it can be delegated
2. In ETH, worked perfectly
3. In DAI, came up as "unknown" and can't be delegated

<img width="925" alt="screen shot 2019-01-03 at 8 51 27 am" src="https://user-images.githubusercontent.com/14945613/50627783-6b561e00-0f35-11e9-929a-58691a0d1e02.png">

**Comment by GriffGreen** [comment]
Added the DAI Reward because I am scared to Donate DAI on the DApp right now..... it might not work.

**Comment by perissology** [comment]
that DAI donation with status == 'unknown' was due to a geth bug (https://github.com/ethereum/go-ethereum/issues/18029).

The other duplicates I'm still investigating, but can assure you that it is not due to the dai integration. A bug in the dai integration just exposed, but is not the cause of, the bug causing the duplicates to appear.

**Comment by perissology** [comment]
Okay, I've determined the cause of the randomly duplicate donations. It was a race condition w/ the failedTxMonitor (due to a bug in the failedTxMonitor) where sometimes a donation would be marked as failed before the tx event was handled.

There was also an error in the config file that may have lead to this issue as well.

Still need to implement a fix for the Geth bug. I'm going to look at that codebase as it may be easier than updating ours. To update ours, requires re-writing a lot of the feathers code to remove the ws use and instead poll for events.
