### ISSUE TITLE
Issue in BETA when deleting Milestone Proof

### ISSUE THREAD

**Issue by MorganGR** [Giveth/giveth-dapp#690]
In the current BETA version when trying to delete a Milestone Proof the button is enabled (big X) and clickable but when clicking and Saving (Updating) the Milestone Proof the line is not removed.
![milestoneproofenabledx](https://user-images.githubusercontent.com/34093087/53497398-f79b4200-3a9b-11e9-9ea2-654015a6c32c.PNG)
![milestoneproofremoved](https://user-images.githubusercontent.com/34093087/53497399-f833d880-3a9b-11e9-85e4-499de0447e51.PNG)

**Comment by ewingrj** [comment]
has this milestone already been created?

**Comment by MorganGR** [comment]
Yes!

**Comment by ewingrj** [comment]
okay, so the bug here is that the "X" is visible. Once a milestone is created, you should not be able to remove a "proof" b/c the proofs are used to calculate the maxAmount of the milestone.

thanks for reporting

**Comment by GriffGreen** [comment]
Simple UI fix just remove the x from being displayed

**Comment by MorganGR** [comment]
@mroberts10 do you know if anyone will look at this? (minor UI fix)

**Comment by mroberts10** [comment]
I will be taking a look at this one now. @MorganGR

**Comment by mroberts10** [comment]
Amin to take a look at this.

**Comment by aminlatifi** [comment]
OK.

**Comment by GriffGreen** [comment]
Might be fixed when andre was working on drafts... to be checked

**Comment by arbreton** [comment]
Fixed in 859

**Comment by aminlatifi** [comment]
I checked out master branch, and test again. The bug still exists.
I recorded a video to show that.
[simplescreenrecorder-2019-06-27_15.48.51.zip](https://github.com/Giveth/giveth-dapp/files/3334357/simplescreenrecorder-2019-06-27_15.48.51.zip)

**Comment by arbreton** [comment]
I couldn’t reproduce the error anymore, the problem was that when you deleted proof when editing it didn’t get deleted, now it deletes fine

**Comment by arbreton** [comment]
If it still needs the “X” to be removed when it has been already created that should be an easy modification 

Assigned to Amin
