### ISSUE TITLE
error uploading new profile picture

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#778]
The profile image on my tertiary account linked to Giveth seems to have been changed?

So I attempted to change it myself and received this error:

![image](https://user-images.githubusercontent.com/39466970/58216021-32d79680-7cc2-11e9-9b19-8fe66df4068a.png)

Upon proceeding further I discovered that @lorelei1 also has a white asterisk on a purple background.. there seems to be a new theme...

![image](https://user-images.githubusercontent.com/39466970/58216164-d3c65180-7cc2-11e9-8d2b-e2ec528ff8c0.png)

**Comment by Danibelle** [comment]
@bowensanders account for Social Coding also impacted:

![image](https://user-images.githubusercontent.com/39466970/58216212-26a00900-7cc3-11e9-84a5-b52fcddef7c3.png)

But not everyone.. @krrisis has not been asterisked.

![image](https://user-images.githubusercontent.com/39466970/58216265-7b438400-7cc3-11e9-8c20-1a9f8ae24365.png)

**Comment by lorelei1** [comment]
Yeah I actually tried to change mine as well as soon as I got asterisked - and got the same error as Dani! Just didn't have the energy to make it an issue, I'm happy to see you're on top of it Dani!

**Comment by Danibelle** [comment]
Update: This appears to be user specific..  Bowen could see his own icon, and my icon simultaneous to me getting the error and asterisks..

**Comment by arbreton** [comment]
Investigating more in depth it seems that there is a problem with the certificate here: **https://ipfs.giveth.io/ipfs/ net::ERR_CERT_DATE_INVALID**, which seems to be causing the issue with all IPFS content, i will take a look on this.

**Comment by arbreton** [comment]
UPDATE: 

We have fixed this problem temporarily, IPFS server on beta has a certificate error, me and @ElMejorge  created a temporal solution, we replaced the IPFS gateway that is causing problems with a temporal HTTPS server gateway, now all the media should be working on beta, as soon as we fix the certificate we would revert back the original IPFS Gateway.

**Comment by krrisis** [comment]
Unfortunately this is still causing errors right now: if you check the Campaign overview you will see that most are also missing their pictures (so not the people but the Campaigns). 

When I created my Milestone ([this one](https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5cebd990ce626b5cebe408bb)) I received the below error, I let it open, signed the transaction and then clicked ok on the error. It seemed to have worked.

![image](https://user-images.githubusercontent.com/6533925/58420262-1904cd80-808d-11e9-8d1e-905c588f3ba1.png)

**Comment by ElMejorge** [comment]
Yeah, the temporary solution is still not 100% stable since the gateway process on the other server is dropped sometimes. I restarted it so that it works again but I still have to set up a new gateway on a Giveth server with proper process management.
