### ISSUE TITLE
Whitelisted Reviewer - Profile not connecting to Address

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#934]
I added two addresses to the Whitelist for Milestone Reviewer.  Jeff Emmett's worked great, he's in there with hs email and name and avatar..
but Coach B is just showing address only at the bottom: 0x580e2BD60625F146bC32C75A63DBe0f61810CCda

![image](https://user-images.githubusercontent.com/39466970/62559975-51691a80-b839-11e9-89d5-9bf548dad519.png)

**Comment by arbreton** [comment]
It is fixed!

**Comment by Danibelle** [comment]
Hey @arbreton - Coach B still does not appear in the Reviewer list, and when I look in Feathers his address is at bottom like this:

![image](https://user-images.githubusercontent.com/39466970/62807424-2c2f1300-baaa-11e9-8876-789e452d2580.png)
